version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Puerto de Prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro  # Configuración de Prometheus
      - prometheus_data:/prometheus  # Datos de Prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Puerto de Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Usuario por defecto
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Contraseña por defecto
    volumes:
      - grafana_data:/var/lib/grafana  # Datos de Grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    volumes:
      - /:/rootfs:ro  # Acceso al sistema para métricas
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Métricas de Docker
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro  # Configuración de Telegraf
    ports:
      - "9273:9273"  # Endpoint Prometheus
    networks:
      - monitoring

volumes:
  prometheus_data: {}  # Volumen para los datos de Prometheus
  grafana_data: {}  # Volumen para los datos de Grafana

networks:
  monitoring:
    
